version: '3.8'
services:
  redis:
    container_name: sp_redis
    image: redis:latest
    ports:
      - 26379:6379
    command: redis-server --requirepass 'password'
  db:
    container_name: sp_db
    image: postgres:13.2
    ports:
      - 25432:5432
    volumes:
      - ./db/docker/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: sp
      POSTGRES_PASSWORD: sp
      POSTGRES_DB: sp
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
