// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/Rusty-Alucard/sp_api/infrastructure/persistence"
	"github.com/Rusty-Alucard/sp_api/usecase"
)

// Injectors from wire.go:

func InitializeEventUseCase() usecase.EventUseCase {
	eventRepository := persistence.NewEventPersistence()
	eventUseCase := usecase.NewEventUseCase(eventRepository)
	return eventUseCase
}

func InitializeTeamUseCase() usecase.TeamUseCase {
	teamRepository := persistence.NewTeamPersistence()
	teamUseCase := usecase.NewTeamUseCase(teamRepository)
	return teamUseCase
}
