# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

dockerhub_auth: $dockerhub_auth
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

executors:
  test:
    working_directory: ~/repo
    docker:
      - image: golang:1.16.3
	    <<: *dockerhub_auth
		environment:
		  TZ: Asia/Tokyo

commands:
  restore_go_mod_cache:
    steps:
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
  save_go_mod_cache:
    steps:
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  install_dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: go mod download
  run_staticcheck:
    steps:
      - run:
          name: Run staticcheck
          command: make staticcheck
  run_unit_test:
    steps:
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
  store_unit_test_results:
    steps:
      - store_test_results:
          path: /tmp/test-reports

jobs:
  build:
    executor: test
    steps:
      - checkout
      - restore_go_mod_cache
      - install_dependencies
      - run_staticcheck
      - run_unit_test
      - save_go_mod_cache
      - store_unit_test_results
